### ISSUE TITLE
Feature request: append `appconfig.json` to published to: `url`

### ISSUE THREAD

**Issue by mostlyfabulous** [Brightspace/frau-publisher#188]
Could we append `appconfig.json` to:
https://github.com/Brightspace/frau-publisher/blob/b1c493ab1883b2bbbb98544c07251587d794aad9/bin/publishercli#L60
before the `\n` character?

This would turn the output from: `https://s.brightspace.com/apps/d2l-class-stream-app/3.365.0/` to: `https://s.brightspace.com/apps/d2l-class-stream-app/3.365.0/appconfig.json`.

Unless this format is intentional.

**Comment by dlockhart** [comment]
This is just in the `console.log` that goes into the build output? I think the main reason it's a bit more vague is that `frau-publisher` is used for both libraries and FRAs. So while FRAs will have an `appconfig.json`, libraries will not.

**Comment by mostlyfabulous** [comment]
> This is just in the `console.log` that goes into the build output?

That's right, makes sense why it is left vague in order to keep it generic.

**Comment by mostlyfabulous** [comment]
If there's a way to get the `moduletype` arg that is passed in to determine whether to append the `appconfig.json` string, perhaps I could open a PR?

> `frau-publisher --moduletype|-m app|lib `

**Comment by dlockhart** [comment]
Absolutely yeah -- I think you should be able to check `opts.moduleType === 'app'`.
