### ISSUE TITLE
Allow overwrites of dev-tagged releases

### ISSUE THREAD

**Issue by jwong-d2l** [Brightspace/frau-publisher#94]
We're doing active development on a project that brings in multiple web-components.  We'd like to be able to click rebuild and get the latest version of the webcomponents published under the same dev-tag.

**Comment by dlockhart** [comment]
So here's the issue with overwriting:

Our CDN is implemented as an S3 bucket with CloudFront in front of it. All the assets in S3 send down a "cache forever" header to browsers. So even if you did overwrite the files, the browser would never ask for a new version.

Additionally, if you overwrote things, CloudFront is still going to keep a copy of the assets on its edge servers. If you want to invalidate those caches, you have to send a special command -- which is expensive $$$.

**Comment by jwong-d2l** [comment]
Maybe something like combining the devtagvar with some sort of generated unique value?

**Comment by dlockhart** [comment]
I'm going to close this. Discussions are happening outside of here about alternative approaches to the problem.
